CAV-670 - Implemented too many requests for email resend
hmrc/cip-email-verification pull request #16
Opened 2022-12-01 23:31 UTC by mar36tin

2022-12-15 10:02 UTC, mar36tin commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +            auditService.sendExplicitAuditEvent(EmailVerificationRequest,
Yes true will update that

2022-12-15 10:02 UTC, johno1985 commented on it/uk/gov/hmrc/cipemailverification/VerifyIntegrationSpec.scala
> +            """{"email": "test1@test.com"}""".stripMargin
do you want to use randomizer here also?

2022-12-15 10:04 UTC, johno1985 reviewed
minor comments

2022-12-15 14:21 UTC, johno1985 commented on README.md
> +#### Verify OTP
this should be passcode

2022-12-15 14:21 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/config/GovNotifyConfig.scala
> -                            protocol: String,
protocol and host need to stay

2022-12-15 14:22 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/config/GovNotifyConfig.scala
> -            config.get[String]("protocol"),
looks like something went wrong with rebase

2022-12-15 14:22 UTC, johno1985 requested changes
problem with rebase

2022-12-15 15:21 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/connectors/GovUkConnector.scala
> +        .transform(_.withRequestFilter(AhcCurlRequestLogger()))
remove this

2022-12-15 15:22 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +        auditService.sendExplicitAuditEvent(EmailVerificationRequest,
I believe the audit event should be logged before the attempt to retrieve the passcode

2022-12-15 15:23 UTC, johno1985 commented on test/uk/gov/hmrc/cipemailverification/connectors/GovUkConnectorSpec.scala
> +//      (
left by mistake?

2022-12-15 15:23 UTC, johno1985 requested changes
pii risk

2022-12-15 16:12 UTC, johno1985 commented on test/uk/gov/hmrc/cipemailverification/services/VerifyServiceSpec.scala
> -      auditServiceMock.sendExplicitAuditEvent(EmailVerificationRequest,
i think we should still verify this

2022-12-15 16:12 UTC, johno1985 reviewed
minor comment

2022-12-16 15:12 UTC, johno1985 commented on it/uk/gov/hmrc/cipemailverification/NotificationIntegrationSpec.scala
> +      val emailRandomizer = Random.alphanumeric.take(10).mkString
use this in the acceptance tests instead of importing additional library

2022-12-16 15:41 UTC, johno1985 commented on test/uk/gov/hmrc/cipemailverification/services/VerifyServiceSpec.scala
> -      auditServiceMock.sendExplicitAuditEvent(EmailVerificationRequest,
this is still absent

2022-12-16 15:43 UTC, merged