CAV-185 - Email service to use Passcode expiry time instead of Cache …
hmrc/cip-email-verification pull request #23
Opened 2023-01-11 16:16 UTC by mar36tin

…expiry time

2023-01-11 16:47 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/controllers/VerifyController.scala
> +      case PasscodeExpiredRequestNew => BadRequest(Json.toJson(
left by mistake?

2023-01-11 16:47 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/models/domain/result/ApplicationError.scala
> +case object PasscodeExpiredRequestNew extends ApplicationError
left by mistake?

2023-01-11 16:48 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +        passcodeService.removePasscode(dataToSave.email)
is this needed? do we not just overwrite what is already there?

2023-01-11 16:48 UTC, johno1985 commented on conf/application.conf
> -  expiry = 2 # minutes
should this not be left as 2?

2023-01-11 16:49 UTC, johno1985 commented on test/uk/gov/hmrc/cipemailverification/services/VerifyServiceSpec.scala
> +    "return Ok if email address is valid and the email database entry(same) already exists, but passcode has expired" in new SetUp {
could we name this test case better?

2023-01-11 16:49 UTC, johno1985 reviewed
minor comments

2023-01-11 17:17 UTC, mar36tin commented on app/uk/gov/hmrc/cipemailverification/controllers/VerifyController.scala
> +      case PasscodeExpiredRequestNew => BadRequest(Json.toJson(
thanks, yes removing

2023-01-12 12:37 UTC, johno1985 commented on test/requests.rest
> +  "email" : "atest65@test.com"
changes left by mistake?

2023-01-12 12:37 UTC, johno1985 reviewed
couple more comments

2023-01-13 10:52 UTC, brdgeth requested changes
a few things to look at please

2023-01-13 10:52 UTC, brdgeth commented on app/uk/gov/hmrc/cipemailverification/services/PasscodeService.scala
> +  def removePasscode(email: String): Future[Option[EmailAndPasscodeData]] = {
yes I don't think we need it either as its done in the db/cache using the TTL.

2023-01-13 10:52 UTC, brdgeth commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +        passcodeService.removePasscode(dataToSave.email)
this doesn't seem quite right.  if its more than the passcode expiry time then they are allowed to be sent another passcode, in which case it will overwrite whatever is in the db/cache.  upsert.  the application doesn't need to delete the existing one.
Maybe you should change change the passcode expiry config variable to something better like passcodeMinimumWaitTime as part of this as its a bit confusing?  Open to suggestions about the name.

2023-01-13 15:05 UTC, mar36tin commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +        passcodeService.removePasscode(dataToSave.email)
@brdgeth can change the name to passcodeMinimumWaitTime but think passcodeExpiry is fine. The only reason why I had to first remove it was because the mongocache is an api and only provides those methods. i.e. delete and insert no update

2023-01-13 16:46 UTC, mar36tin commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +        passcodeService.removePasscode(dataToSave.email)
yes done

2023-01-16 11:30 UTC, johno1985 commented
still some merge conflitcs that need resolving

2023-01-17 10:41 UTC, johno1985 commented on app/uk/gov/hmrc/cipemailverification/services/VerifyHelper.scala
> +  private def futureErrorHandler(err: Throwable) = {
is this the same as errorHandler? And could it have a better name?

2023-01-17 10:42 UTC, johno1985 reviewed
minor comment

2023-01-17 16:14 UTC, johno1985 approved these changes

2023-01-19 10:16 UTC, merged